
SELECT
       DISTINCT(C.GROUP_NAME) as OBJECT_TAB, CASE WHEN UPPER(C.TLOGO) = 'PSA' then E.USEROBJ when UPPER(C.TLOGO) = 'DTP' then E.USEROBJ  WHEN UPPER(C.TLOGO) = 'NHUB' then REPLACE(C.GROUP_NAME,'/BIC/OH','') ELSE C.GROUP_NAME END OBJECT_NAME,
	   REPLACE(REPLACE(UPPER(C.TLOGO),'PSA','RSDS'),'NHUB','DEST') as TLOGO, C.GROUP_TYPE as GROUP_NAME, SUM(A.RECORD_COUNT) AS RECORD_COUNT, SUM(A.MEMORY_SIZE) as MEMORY_SIZE_GB, SUM(D.DISK_SIZE) as DISK_SIZE_GB
FROM ( SELECT '%' SCHEMA_NAME, '%' TABLE_NAME, '%' GROUP_NAME, '%' TLOGO, '%' GROUP_TYPE, '%' SUBTYPE FROM DUMMY ) BI,
	 ( SELECT CT.SCHEMA_NAME, CT.TABLE_NAME, CT.RECORD_COUNT,TO_DECIMAL(CT.TABLE_SIZE/1024/1024/1024, 10,2) as MEMORY_SIZE, CT.IS_PARTITIONED FROM M_TABLES CT ) A,
	 ( SELECT TG.TABLE_NAME, TG.GROUP_NAME, TG.SUBTYPE, CASE WHEN TG.SUBTYPE = 'ACTIVE' 
THEN
              CASE
              WHEN RIGHT(TG.TABLE_NAME,1) = '2'
              THEN 'ADSO'
              WHEN RIGHT(TG.TABLE_NAME,1) = '0'
              THEN 'ODSO'
              END
 
 
WHEN TG.SUBTYPE = 'CHANGE_LOG'
THEN
              CASE
              WHEN RIGHT(TG.TABLE_NAME,1) = '3'
              THEN 'ADSO'
              WHEN RIGHT(TG.TABLE_NAME,1) = '0'
              THEN 'ODSO'
              END
WHEN TG.SUBTYPE = 'QUEUE'
THEN
              CASE
              WHEN RIGHT(TG.TABLE_NAME,1) = '1'
              THEN 'ADSO'
              WHEN RIGHT(TG.TABLE_NAME,1) = '0'
              THEN 'ODSO'
              END
ELSE REPLACE(REPLACE(RIGHT(TG.GROUP_TYPE,4),'.',''),'_','')
END TLOGO, TG.GROUP_TYPE FROM TABLE_GROUPS TG ) C,
( SELECT DS.SCHEMA_NAME,DS.TABLE_NAME,TO_DECIMAL(DS.DISK_SIZE/1024/1024/1024,10,2) as DISK_SIZE FROM M_TABLE_PERSISTENCE_STATISTICS DS ) D 
left join (select  ODSNAME_TECH, USEROBJ from "RSTSODS" ) E on D.TABLE_NAME = E.ODSNAME_TECH
WHERE A.SCHEMA_NAME LIKE BI.SCHEMA_NAME 
AND A.TABLE_NAME LIKE BI.TABLE_NAME 
AND C.GROUP_NAME LIKE BI.GROUP_NAME 
AND C.GROUP_TYPE LIKE BI.GROUP_TYPE 
AND C.TLOGO LIKE BI.TLOGO 
AND C.SUBTYPE LIKE BI.SUBTYPE  
AND C.TABLE_NAME = A.TABLE_NAME 
AND D.SCHEMA_NAME LIKE BI.SCHEMA_NAME 
AND D.TABLE_NAME LIKE BI.TABLE_NAME 
AND A.TABLE_NAME = D.TABLE_NAME  
group by C.GROUP_NAME ,C.TLOGO,C.GROUP_TYPE, E.USEROBJ
ORDER BY C.TLOGO ASC 